using UnityEngine;
using System;
using System.Collections.Generic;

public class OrganManager : MonoBehaviour
{
public static OrganManager Instance { get; private set; }
    
    public List<OrganData> organs = new List<OrganData>();
    public int totalEnergy;  // Store total energy generated by organs

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);  // Keeps the manager across scenes
        }
        else
        {
            Destroy(gameObject);
        }
    }

    private void Start()
    {
        // Restore state (e.g., load saved organ data)
        LoadOrganData();
    }

    private void Update()
    {
    }

    public void AddOrgan(OrganData newOrgan)
    {
        organs.Add(newOrgan);
    }

    public void SaveOrganData()
    {
        // Save organ data persistently (e.g., using PlayerPrefs or writing to a file)
    }

    public void LoadOrganData()
    {
        // Load organ data from persistent storage
    }
}
